#############################################################################
# Makefile for building: Laplacian3D
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Mar 19 11:32:28 2014
# Project:  Laplacian3D.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Laplacian3D.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I/usr/include/mumps_seq -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lblas -lgfortran -lmpiseq_seq -lmumps_common_seq -ldmumps_seq -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = allocateModel.cpp \
		allocateModelData.cpp \
		Main.cpp \
		MUMPSSolver.cpp \
		saveModelData.cpp \
		setAnalysis.cpp \
		setForceVector.cpp \
		setMeshRefiner.cpp \
		setModelData.cpp \
		setModelDofs.cpp \
		setStiffnessMatrix.cpp \
		setTotalError.cpp 
OBJECTS       = allocateModel.o \
		allocateModelData.o \
		Main.o \
		MUMPSSolver.o \
		saveModelData.o \
		setAnalysis.o \
		setForceVector.o \
		setMeshRefiner.o \
		setModelData.o \
		setModelDofs.o \
		setStiffnessMatrix.o \
		setTotalError.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Laplacian3D.pro
QMAKE_TARGET  = Laplacian3D
DESTDIR       = 
TARGET        = Laplacian3D

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Laplacian3D.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Laplacian3D.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Laplacian3D.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Laplacian3D1.0.0 || $(MKDIR) .tmp/Laplacian3D1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Laplacian3D1.0.0/ && $(COPY_FILE) --parents allocateModel.hh allocateModelData.hh MUMPSSolver.hh saveModelData.hh setAnalysis.hh setForceVector.hh setMeshRefiner.hh setModelData.hh setModelDofs.hh setStiffnessMatrix.hh setTotalError.hh .tmp/Laplacian3D1.0.0/ && $(COPY_FILE) --parents allocateModel.cpp allocateModelData.cpp Main.cpp MUMPSSolver.cpp saveModelData.cpp setAnalysis.cpp setForceVector.cpp setMeshRefiner.cpp setModelData.cpp setModelDofs.cpp setStiffnessMatrix.cpp setTotalError.cpp .tmp/Laplacian3D1.0.0/ && (cd `dirname .tmp/Laplacian3D1.0.0` && $(TAR) Laplacian3D1.0.0.tar Laplacian3D1.0.0 && $(COMPRESS) Laplacian3D1.0.0.tar) && $(MOVE) `dirname .tmp/Laplacian3D1.0.0`/Laplacian3D1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Laplacian3D1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

allocateModel.o: allocateModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o allocateModel.o allocateModel.cpp

allocateModelData.o: allocateModelData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o allocateModelData.o allocateModelData.cpp

Main.o: Main.cpp setAnalysis.hh \
		MUMPSSolver.hh \
		setModelData.hh \
		setModelDofs.hh \
		setTotalError.hh \
		saveModelData.hh \
		allocateModel.hh \
		setForceVector.hh \
		setMeshRefiner.hh \
		setStiffnessMatrix.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

MUMPSSolver.o: MUMPSSolver.cpp MUMPSSolver.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MUMPSSolver.o MUMPSSolver.cpp

saveModelData.o: saveModelData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveModelData.o saveModelData.cpp

setAnalysis.o: setAnalysis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setAnalysis.o setAnalysis.cpp

setForceVector.o: setForceVector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setForceVector.o setForceVector.cpp

setMeshRefiner.o: setMeshRefiner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setMeshRefiner.o setMeshRefiner.cpp

setModelData.o: setModelData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setModelData.o setModelData.cpp

setModelDofs.o: setModelDofs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setModelDofs.o setModelDofs.cpp

setStiffnessMatrix.o: setStiffnessMatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setStiffnessMatrix.o setStiffnessMatrix.cpp

setTotalError.o: setTotalError.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setTotalError.o setTotalError.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

